### ISSUE TITLE
项目相关

### ISSUE THREAD

**Issue by andoloido** [fmtjava/Jetpack_GitHub#1]
请问这个项目有用屏幕适配吗，看代码好像是没有

**Comment by fmtjava** [comment]
暂时使用传统的dp,sp进行适配，这块后续可以优化一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"toolperson"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月30日(星期四) 下午3:30
收件人:&nbsp;"fmtjava/Jetpack_GitHub"<Jetpack_GitHub@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[fmtjava/Jetpack_GitHub] 项目相关 (#1)





 
请问这个项目有用屏幕适配吗，看代码好像是没有

**Comment by andoloido** [comment]
明白了
