### ISSUE TITLE
Oauth Authorization callback URL 如何配合

### ISSUE THREAD

**Issue by yangxiaoge** [fmtjava/Jetpack_GitHub#12]
如题：
![image](https://user-images.githubusercontent.com/12471093/109271019-e54e6d00-7849-11eb-9f7f-19079992fbb9.png)
我是这么配置的，但是无法回跳到我写的应用中。

**Comment by fmtjava** [comment]
试一下下面的步骤：

第一步：
![image](https://user-images.githubusercontent.com/16126424/109272045-4f1b4680-784b-11eb-8694-2add43f9ea2d.png)
第二步：
![image](https://user-images.githubusercontent.com/16126424/109272096-60645300-784b-11eb-87f0-065f539fef3d.png)

**Comment by yangxiaoge** [comment]
> 试一下下面的步骤：
> 
> 第一步：
> ![image](https://user-images.githubusercontent.com/16126424/109272045-4f1b4680-784b-11eb-8694-2add43f9ea2d.png)
> 第二步：
> ![image](https://user-images.githubusercontent.com/16126424/109272096-60645300-784b-11eb-87f0-065f539fef3d.png)

谢谢，现在可以回掉到app了，然后还有一个疑问，就是code与state是怎么配置的呢
![image](https://user-images.githubusercontent.com/12471093/109273214-db7a3900-784c-11eb-9e11-922e29e6d75d.png)

**Comment by fmtjava** [comment]
这个不需要配置啊，授权后从Intent中获取即可

**Comment by yangxiaoge** [comment]
> 这个不需要配置啊，授权后从Intent中获取即可

明白了，多谢回复！😁
