### ISSUE TITLE
Settings file 'E:\download\Jetpack_GitHub-master\settings.gradle' line: 4

### ISSUE THREAD

**Issue by hyk12345** [fmtjava/Jetpack_GitHub#13]
A problem occurred evaluating settings 'Jetpack_GitHub-master'.
> E:\download\flutter_module\.android\include_flutter.groovy (E:\download\flutter_module\.android\include_flutter.groovy)

**Comment by fmtjava** [comment]
第一步：clone https://github.com/fmtjava/Jetpeck_Flutter_Trend.git这个项目
第二步：Android studio打开上面克隆的项目，并同步flutter插件
![image](https://user-images.githubusercontent.com/16126424/123730613-3f7b3f80-d8c9-11eb-9c0c-c4b4e2907c37.png)
第三步：clone https://github.com/fmtjava/Jetpack_GitHub.git这个项目(注意项目存放路径要和第一步一致),Android studio打开sync同步就能运行了

**Comment by fmtjava** [comment]
已调整项目工程结构，只需clone https://github.com/fmtjava/Jetpack_GitHub.git这个项目同步即可
