### ISSUE TITLE
大佬有个问题请教

### ISSUE THREAD

**Issue by wumingshicong** [fmtjava/Jetpack_GitHub#14]
<img width="949" alt="image" src="https://user-images.githubusercontent.com/48897139/182574997-30be567b-1e3b-4d2b-864d-482231390d83.png">

**Comment by wumingshicong** [comment]
初学者

**Comment by fmtjava** [comment]
BR 这个DataBinding自动生成的，common_refresh_recyclerview.*这个文件是kotlin-extensions插件帮我们生成的

**Comment by wumingshicong** [comment]
要怎么操作可以自动生成

**Comment by fmtjava** [comment]
不要操作，build.gradle中添加
apply plugin: 'kotlin-android-extensions'
和
dataBinding {
       enabled true
    }
  即可，这些都是很基础的配置，可以去网上查查相关的资料
