### ISSUE TITLE
检查更新好像出了点问题？

### ISSUE THREAD

**Issue by andoloido** [fmtjava/Jetpack_GitHub#3]
![image](https://user-images.githubusercontent.com/52614822/81133717-14c37e80-8f85-11ea-871a-aaa7c4ef6f00.png)
如图，我水平有限看不太出来，但是确实是logout的时候才检查了更新，好像是和协程有些关系吧？

**Comment by fmtjava** [comment]
和协程没有关系吧，这边协程不会阻塞检查更新，可以看一下log日志的打印就知道了
