### ISSUE TITLE
请问如果要对返回值封装处理，用emit该怎么处理呢

### ISSUE THREAD

**Issue by wsmzdyss** [fmtjava/Jetpack_GitHub#7]
请问如果要对返回值封装处理，用emit该怎么处理呢

**Comment by fmtjava** [comment]
封装处理具体指那种方式，是要返回一个BaseResponse吗？

**Comment by wsmzdyss** [comment]
> 封装处理具体指那种方式，是要返回一个BaseResponse吗？

是的，比如对返回里的自定义状态码做统一判断之类的

**Comment by fmtjava** [comment]
类似于这样的伪代码:
fun <T> emitTest(block: suspend LiveDataScope<HttpKtResponse<T>>.() -> HttpKtResponse<T>): LiveData<HttpKtResponse<T>> =
        liveData {
            try {
                mStateLiveData.value = LoadState
                val response = block()
                if (response.success) {
                    emit(response)
                    mStateLiveData.value = SuccessState
                } else {
                    throw Exception(response.message)
                }
            } catch (e: Exception) {
                mStateLiveData.value = ErrorState(e.message)
            }
        }

**Comment by wsmzdyss** [comment]
好的，感谢
