### ISSUE TITLE
BaseViewModel里封装的emit返回livedata是否有性能问题？

### ISSUE THREAD

**Issue by nemo-ex** [fmtjava/Jetpack_GitHub#8]
```kotlin
fun searchRepos(
    query: String,
    sort: String,
    order: String,
    page: Int
): LiveData<List<ReposItemModel>> = emit {
    mReposRepository.searchRepos(query, sort, order, page).items
}
```
比如上面的案例，每次调用searchRepos就返回一个新的liveData，并且绑定到lifecycler，如果调用了很多次的时候是不是可能有性能问题。小白初次使用livedata和协程，请教下大佬

**Comment by fmtjava** [comment]
这个影响不大，你可以使用Android Profiler看一下内存使用情况

**Comment by nemo-ex** [comment]
> 这个影响不大，你可以使用Android Profiler看一下内存使用情况

那就是说是如果某个页面常驻太多次调用的时候就可能有性能问题吧？有点小强迫症，准备换种写法去用好了-_-!

**Comment by fmtjava** [comment]
你也可以把LiveData声明为成员变量，每次获取到数据后，重新setValue就可以了

**Comment by nemo-ex** [comment]
好的，谢谢
